### ISSUE TITLE
No CLOCK_REALTIME/clock_gettime on OSX

### ISSUE THREAD

**Issue by simt2** [gkdr/lurch#9]
Trying to compile on OS X 10.11.6:
```
 make
cd ./lib/axc/lib/libaxolotl-c/ && mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/miku/src/lurch/lib/axc/lib/libaxolotl-c/build
[  1%] Built target protobuf-c
[ 67%] Built target curve25519
[100%] Built target axolotl-c
cd ./lib/axc && make axc-pic
gcc -fPIC -I./lib/libaxolotl-c/src -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -fno-builtin-memset -c src/axc.c -o build/axc.o
src/axc.c:610:28: warning: missing field 'tv_nsec' initializer [-Wmissing-field-initializers]
  struct timespec time = {0};
                           ^
src/axc.c:711:15: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    ret_val = clock_gettime(CLOCK_REALTIME, &time);
              ^
src/axc.c:711:29: error: use of undeclared identifier 'CLOCK_REALTIME'
    ret_val = clock_gettime(CLOCK_REALTIME, &time);
                            ^
2 warnings and 1 error generated.
make[1]: *** [axc.o] Error 1
make: *** [axc] Error 2
```

**Comment by simt2** [comment]
It seems like `clock_gettime` is available on OSX 10.12 though. Not sure if supporting anything but the current version of OSX/MacOS is necessary.

**Comment by EionRobb** [comment]
Same issue on Win32:
```
src/axc.c: In function 'axc_install':
src/axc.c:711:5: warning: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
src/axc.c:711:29: error: 'CLOCK_REALTIME' undeclared (first use in this function)
```

You could try using `g_get_real_time()` instead?

**Comment by gkdr** [comment]
For the record, sem_init also does not exist on OSX and has to be replaced with sem_open.

**Comment by gkdr** [comment]
I replaced this function in cb081fd6a9509a2fcd23b61f6f31ed38324b3505 as suggested.
